apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: springboot-replicate
spec:
  selector:
    matchLabels:
      app: springboot-replicate
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: springboot-replicate
    spec:
      containers:
        - name: springboot-replicate
          image: custom-replication:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster