version: '3.8'

services:
  postgresql-master:
    image: bitnami/postgresql:16-debian-11
    ports:
      - '5333:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=admin123
      - POSTGRESQL_DATABASE=repl_database

  postgresql-slave:
    image: bitnami/postgresql:16-debian-11
    ports:
      - '5334:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=admin123
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432

volumes:
  postgresql_master_data:
    driver: local