apiVersion: v1
kind: Service
metadata: # Metadata of the resource kind we are creating
  name: replicate-service
spec:
  selector:
    app: springboot-replicate
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.